# Generated by Django 5.2.6 on 2025-09-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_city_province_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='accounts_ad_provinc_09fa27_idx',
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(max_length=255, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=255, verbose_name=' توضیحات آدرس'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_type'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
