# Generated by Django 5.2.6 on 2025-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_city_province_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='line2',
        ),
        migrations.AddField(
            model_name='address',
            name='address_exact',
            field=models.CharField(default='نامشخص', max_length=255, verbose_name='آدرس دقیق'),
        ),
        migrations.AddField(
            model_name='address',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیحات'),
        ),
    ]
