# Generated by Django 5.2.6 on 2025-09-29 07:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_coupon_order_coupon_code_order_discount_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('init', 'ایجاد شده'), ('started', 'ارسال به درگاه'), ('success', 'موفق'), ('failed', 'ناموفق')], default='init', max_length=16, verbose_name='وضعیت')),
                ('authority', models.CharField(blank=True, max_length=64, verbose_name='شناسه درگاه/Authority')),
                ('ref_id', models.CharField(blank=True, max_length=64, verbose_name='کد پیگیری')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
