# Generated by Django 5.2.6 on 2025-09-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(blank=True, help_text='مثال: #000000', max_length=7, verbose_name='کد HEX (اختیاری)'),
        ),
        migrations.AddField(
            model_name='size',
            name='code',
            field=models.CharField(blank=True, help_text='مثل: S, M, L, 38, 40 …', max_length=32, null=True, verbose_name='کد یکتای سایز'),
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(blank=True, help_text='مثل: RED, BLK, CRM …', max_length=32, null=True, verbose_name='کد یکتای رنگ'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=20, verbose_name='سایز'),
        ),
    ]
