# Generated by Django 5.2.6 (fixed)
from django.db import migrations, models
from django.utils.text import slugify


def fill_unique_codes(apps, schema_editor):
    Color = apps.get_model('products', 'Color')
    Size  = apps.get_model('products', 'Size')

    # ---- Color.code: پر و یکتا ----
    existing = set(
        Color.objects.exclude(code__isnull=True).exclude(code="").values_list("code", flat=True)
    )
    for c in Color.objects.all().order_by("id"):
        val = (c.code or "").strip()
        if not val or val in existing:
            base = slugify(c.name or "", allow_unicode=True).upper()
            if not base:
                base = f"CLR{c.pk}"
            base = (base[:6] or "CLR")
            candidate = base
            i = 1
            while candidate in existing or Color.objects.exclude(pk=c.pk).filter(code=candidate).exists():
                i += 1
                candidate = f"{base}{i}"
            c.code = candidate
            c.save(update_fields=["code"])
            existing.add(candidate)
        else:
            existing.add(val)

    # ---- Size.code: پر و یکتا ----
    existing = set(
        Size.objects.exclude(code__isnull=True).exclude(code="").values_list("code", flat=True)
    )
    for s in Size.objects.all().order_by("id"):
        val = (s.code or "").strip()
        if not val or val in existing:
            base = slugify(s.name or "", allow_unicode=True).upper()
            if not base:
                base = f"SIZ{s.pk}"
            base = (base[:6] or "SIZ")
            candidate = base
            i = 1
            while candidate in existing or Size.objects.exclude(pk=s.pk).filter(code=candidate).exists():
                i += 1
                candidate = f"{base}{i}"
            s.code = candidate
            s.save(update_fields=["code"])
            existing.add(candidate)
        else:
            existing.add(val)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_color_hex_code_size_code_alter_color_code_and_more'),
    ]

    operations = [
        # 1) اول داده‌ها را یکتا کن تا یونیک خطا ندهد
        migrations.RunPython(fill_unique_codes, migrations.RunPython.noop),

        # 2) سپس unique=True را اعمال کن
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(
                verbose_name='کد یکتای رنگ',
                max_length=32, blank=True, null=True, unique=True,
                help_text='مثل: RED, BLK, CRM …',
            ),
        ),
        migrations.AlterField(
            model_name='size',
            name='code',
            field=models.CharField(
                verbose_name='کد یکتای سایز',
                max_length=32, blank=True, null=True, unique=True,
                help_text='مثل: S, M, L, 38, 40 …',
            ),
        ),
    ]
